services:
  postgres:
    image: postgres:17.9-alpine
    container_name: dockhand-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: dockhand
    volumes:
      - ${DOCKHAND_POSTGRES_DATA_FOLDER:-./data/dockhand/db}:/var/lib/postgresql/data
    restart: always
    networks:
      external:
        ipv4_address: ${POSTGRES_IP}

  dockhand:
    image: fnsys/dockhand
    container_name: dockhand-app
    environment:
      DATABASE_URL: postgres://admin:${POSTGRES_PASSWORD}@${POSTGRES_IP}:5432/dockhand
    volumes:
      - ${DOCKHAND_DATA_FOLDER:-./data/dockhand}:/app/data
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      external:
        ipv4_address: ${DOCKHAND_IP}

networks:
  external:
    external: true
    name: ${EXTERNAL_NETWORK_NAME}