services:
  postgres:
    image: postgres:17.9-alpine
    container_name: dockhand-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: dockhand
    volumes:
      - ./data/dockhand/db:/var/lib/postgresql/data
    restart: always
    networks:
      local:

  dockhand:
    image: fnsys/dockhand
    container_name: dockhand-app
    environment:
      DATABASE_URL: postgres://admin:${POSTGRES_PASSWORD}@postgres:5432/dockhand
    volumes:
      - ./data/dockhand:/app/data
    depends_on:
      - postgres
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      local:

networks:
  local:
    name: dockhand-local-network