services:
  dockhand:
    image: fnsys/dockhand
    container_name: dockhand
    hostname: dockhand
    volumes:
      - ${DOCKHAND_DATA_FOLDER:-./data/dockhand}:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      external:
        ipv4_address: ${DOCKHAND_IP}

networks:
  external:
    external: true
    name: ${EXTERNAL_NETWORK_NAME}