services:
  postgres:
    image: postgres:16-alpine
    container_name: dockhand-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - ${DOCKHAND_DBDATA_FOLDER:-./dbdata}:/var/lib/postgresql/data
    restart: always
    networks:
      local:

  dockhand:
    image: fnsys/dockhand
    container_name: dockhand-app
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB_NAME}
    volumes:
      - ${DOCKHAND_DATA_FOLDER:-./data}:/app/data
    depends_on:
      - postgres
    restart: unless-stopped
    ports:
      - ${DOCKHAND_PORT:-3000}:3000
    networks:
      local:

networks:
  local:
    name: dockhand-local-network